# Generated by Django 5.2.10 on 2026-03-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_creator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.user'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.post'),
        ),
    ]
